spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      auto-commit: false
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 20
      max-lifetime: 1_000_000
      connection-timeout: 30_000
